artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://github.com/omaar25/data/raw/refs/heads/main/maintenace_predictive.zip"  # URL for downloading
  local_data_file: "artifacts/data_ingestion/data.zip"  # Local path to the zip file
  unzip_dir: artifacts/data_ingestion  # Directory where the zip will be extracted


data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/predictive_maintenance.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_processing:
  root_dir : artifacts/data_processing
  data_path : artifacts/data_ingestion/predictive_maintenance.csv





